import os
import pandas as pd

from imppkg.simplifiedSA import uniquify, download_df

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PRODUCED_TEST_FILES_DIR = os.path.join(CURRENT_DIR,"produced_files")

test_data = {'Letter':["A", "B", "C", "D"],
             'Index': ["0", "1", "2", "3"],
             'Score':[0.234, 0.948, 0.23, 0]
            }
 
test_df = pd.DataFrame(test_data)

def test_download_df_all_args(test_df):
    download_df(test_df, title="Test DataFrame", save_filepath=CURRENT_DIR, 
                filename_suffix='_test_DF', date=True)

    expected_file_path = os.path.join(CURRENT_DIR, 'expectedFileNameIDKDKDKKD')

    assert os.path.exists(expected_file_path)

# def test_uniquify():
    # uniquify()
    
# Delete the files generated by this test program
for file in os.listdir(PRODUCED_TEST_FILES_DIR):
    file_path = os.path.join(PRODUCED_TEST_FILES_DIR, file)
    if os.path.isfile(file_path):
        os.remove(file_path)